#!/usr/bin/env bash
# Tingopix — An open DIY film scanner for 8mm, Regular 8, Super 8, and 16mm.
# Sensel-native, archival-first.
#
# Copyright (c) 2026 Pablo Miliani / Tingopix
# Project: https://github.com/tingopix/tingopix-one
# Website: https://tingopix.github.io
#
# SPDX-License-Identifier: MIT
# Licensed under the MIT License. See LICENSE file in the project root for full text.

# One-line install:
#   curl -fsSL https://raw.githubusercontent.com/tingopix/tingopix-one/main/install.sh | bash
#
# Runs as a normal user. sudo is invoked only for apt and /usr/local/bin writes.

set -euo pipefail

REPO_URL="https://github.com/tingopix/tingopix-one"
CLONE_DIR="$HOME/tingopix-one"
APP_DIR="$CLONE_DIR/software-rpi"
VENV_DIR="$APP_DIR/env-tpx"
WRAPPER="/usr/local/bin/tingopix"
UPDATER="/usr/local/bin/tingopix-update"
POST_DIR="$CLONE_DIR/postprocess"
POSTPROC="/usr/local/bin/tingopix-postprocess"
DESKTOP="$HOME/.local/share/applications/tingopix.desktop"
ICON_DIR="$HOME/.local/share/icons/hicolor/256x256/apps"
ICON="$ICON_DIR/tpx_icon.png"

say()  { printf '\n\033[1;33m[tingopix]\033[0m %s\n' "$1"; }
die()  { printf '\n\033[1;31m[tingopix] ERROR:\033[0m %s\n' "$1" >&2; exit 1; }

# --- preflight ---------------------------------------------------------------

command -v git >/dev/null 2>&1 || die "git not found. Install it and re-run."
command -v python3 >/dev/null 2>&1 || die "python3 not found."

# --- apt dependencies --------------------------------------------------------
# Only the two packages missing from a stock Pi OS image. Everything else
# (python3-gi, python3-picamera2, numpy, psutil, pyserial, git, python3-venv)
# ships preinstalled and must NOT be touched — pip-installing picamera2 or
# numpy would shadow the working system builds.

say "Installing apt dependencies (gir1.2-gtk-4.0, python3-gi-cairo)..."
sudo apt-get update
sudo apt-get install -y gir1.2-gtk-4.0 python3-gi-cairo

# --- clone or update ---------------------------------------------------------

if [ -e "$CLONE_DIR" ]; then
    if [ -d "$CLONE_DIR/.git" ] && \
       git -C "$CLONE_DIR" remote get-url origin 2>/dev/null | grep -q "tingopix-one"; then
        say "Existing Tingopix clone found at $CLONE_DIR — updating (git pull)..."
        git -C "$CLONE_DIR" pull --ff-only
    else
        die "$CLONE_DIR already exists and is not a Tingopix clone. Refusing to overwrite. Move or remove it and re-run."
    fi
else
    say "Cloning $REPO_URL (main) to $CLONE_DIR..."
    git clone "$REPO_URL" "$CLONE_DIR"
fi

[ -d "$APP_DIR" ] || die "Expected app directory not found: $APP_DIR"
[ -d "$POST_DIR" ] || die "Expected postprocess directory not found: $POST_DIR"

# --- virtual environment -----------------------------------------------------
# --system-site-packages so the venv inherits the system picamera2 / numpy /
# GTK bindings; only numba and tifffile get installed into it.

if [ -d "$VENV_DIR" ]; then
    say "Reusing existing venv at $VENV_DIR..."
else
    say "Creating venv (--system-site-packages) at $VENV_DIR..."
    python3 -m venv --system-site-packages "$VENV_DIR"
fi

# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"

say "Installing pip dependencies (numba, tifffile)..."
pip install --upgrade pip
pip install -r "$APP_DIR/requirements.txt"

# --- numpy shadow guard (abort-only) -----------------------------------------
# pip pulls numpy transitively via numba. With --system-site-packages, a
# venv-local numpy would take precedence over the picamera2-compatible system
# build and crash at first launch. Match the FORBIDDEN location (the venv);
# a pass means numpy resolved to the system dist-packages.

say "Verifying numpy did not shadow the system build..."
NUMPY_PATH="$(python -c 'import numpy; print(numpy.__file__)')"
case "$NUMPY_PATH" in
    "$VENV_DIR"/*)
        die "numpy resolved INTO the venv ($NUMPY_PATH), shadowing the system build picamera2 depends on.
       Fix: 'source $VENV_DIR/bin/activate && pip uninstall numpy', then re-run this installer." ;;
    *)
        say "OK — numpy resolves to $NUMPY_PATH" ;;
esac

deactivate

# --- system wrapper ----------------------------------------------------------
# Activates the venv, cds to the app dir (so numba_cache/ lands there and is
# reused regardless of launch cwd), execs main.py. Home path is hardcoded for
# the installing user.

say "Installing wrapper $WRAPPER (sudo)..."
sudo tee "$WRAPPER" >/dev/null <<EOF
#!/usr/bin/env bash
# Tingopix launcher — generated by install.sh
source "$VENV_DIR/bin/activate"
cd "$APP_DIR"
exec python main.py "\$@"
EOF
sudo chmod +x "$WRAPPER"

# --- system updater ----------------------------------------------------------

say "Installing updater $UPDATER (sudo)..."
sudo tee "$UPDATER" >/dev/null <<EOF
#!/usr/bin/env bash
# Tingopix updater — generated by install.sh
set -euo pipefail
echo "[tingopix-update] Pulling latest main..."
git -C "$CLONE_DIR" pull --ff-only
echo "[tingopix-update] Updating pip dependencies..."
source "$VENV_DIR/bin/activate"
pip install -r "$APP_DIR/requirements.txt"
deactivate
echo "[tingopix-update] Done."
EOF
sudo chmod +x "$UPDATER"

# --- post-scan processing wrapper --------------------------------------------
# For spot-checking raw frames on the Pi itself. The venv already provides
# numpy, numba and tifffile, so nothing extra is installed here. Note that
# postprocess/requirements.txt is deliberately NOT used: it lists numpy, and
# pip-installing that into this --system-site-packages venv would shadow the
# system build picamera2 depends on. cd into postprocess/ so numba's compile
# cache lands there and is reused regardless of the launch directory.

say "Installing wrapper $POSTPROC (sudo)..."
sudo tee "$POSTPROC" >/dev/null <<EOF
#!/usr/bin/env bash
# Tingopix post-scan processing — generated by install.sh
source "$VENV_DIR/bin/activate"
cd "$POST_DIR"
exec python debayer_vng.py "\$@"
EOF
sudo chmod +x "$POSTPROC"

# --- icon --------------------------------------------------------------------

say "Installing icon..."
mkdir -p "$ICON_DIR"
cp "$APP_DIR/tpx_icon.png" "$ICON"

# --- desktop entry -----------------------------------------------------------
# Terminal=true: first run compiles the numba warm-ups (~100 s) before the GTK
# window appears; a detached launch would look hung. The terminal shows the
# COMPILE_ETA log output. Tradeoff: it sits behind the window, and closing it
# kills the app.

say "Installing desktop entry $DESKTOP..."
mkdir -p "$(dirname "$DESKTOP")"
cat > "$DESKTOP" <<EOF
[Desktop Entry]
Type=Application
Name=Tingopix
Comment=Open DIY film scanner
Exec=$WRAPPER
Icon=$ICON
Terminal=true
Categories=Graphics;Photography;
EOF
chmod +x "$DESKTOP"

update-desktop-database "$(dirname "$DESKTOP")" 2>/dev/null || true

# --- done --------------------------------------------------------------------

say "Installation complete."
cat <<EOF

  Launch Tingopix from the applications menu, or run:  tingopix
  Update later with:                                   sudo tingopix-update
  Spot-check a raw frame with:                         tingopix-postprocess in.tif out.tif

  NOTE: the FIRST launch compiles the Numba warm-ups and takes about 100
  seconds before the window appears (roughly 8 seconds on later runs). This
  is normal — watch the terminal for the compile progress and ETA output.

EOF
